# Name of the Spring Boot application
spring.application.name=portfolio-backend

# Gmail SMTP server configuration for sending emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Enables SMTP authentication and secure TLS connection
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Imports local secret configuration containing sensitive credentials
spring.config.import=optional:application-secret.properties