# Name of the Spring Boot application
spring.application.name=portfolio-backend

# Gmail SMTP server configuration for sending emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Enables SMTP authentication and secure TLS connection
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true